name: APK Extractor and Release Publisher

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 15 * * *' # Roda todos os dias às 12:00 (Meio-dia no Horário de Brasília)
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Permite que o GitHub leia o histórico para gerar as notas de lançamento

    - name: Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install required dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run APK Extractor Bot
      id: bot
      run: python check_builds.py

    # Monta os links fixos que você quer no topo das notas
    - name: Pre-fill Release Content
      if: steps.bot.outputs.tag != ''
      run: |
        echo "- Link: **https://libretro.com**" > release_notes.txt
        echo "- Código fonte: **https://libretro.comlatest/**" >> release_notes.txt
        echo "" >> release_notes.txt

    - name: Create and Publish GitHub Release
      if: steps.bot.outputs.tag != ''
      run: |
        NEW_TAG="${{ steps.bot.outputs.tag }}"
        
        # O parâmetro --generate-notes cria automaticamente a seção "Full Changelog" nativa no fim do texto
        gh release create "$NEW_TAG" downloaded_apks/* \
          --title "${NEW_TAG}-RetroArch" \
          --notes-file release_notes.txt \
          --generate-notes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
